// Build the Lit panel into a single ESM bundle that Home Assistant serves as a
// static module. The integration ships this committed artifact because HACS and
// manual installs cannot run a JS toolchain. Run `npm run build` after changing
// anything under src/.
import { build, context } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const outfile = resolve(
  here,
  "../custom_components/boat_management/frontend/boat-management-panel.js",
);

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: [resolve(here, "src/main.ts")],
  outfile,
  bundle: true,
  format: "esm",
  target: "es2020",
  minify: true,
  sourcemap: false,
  legalComments: "none",
  // Lit ships browser-ready ESM; bundle it so the artifact is self-contained
  // and needs no import map at runtime.
  banner: {
    js: "/* boat-management-panel — generated by frontend/build.mjs. Do not edit by hand. */",
  },
};

const watch = process.argv.includes("--watch");

if (watch) {
  const ctx = await context(options);
  await ctx.watch();
  // eslint-disable-next-line no-console
  console.log("watching frontend src -> " + outfile);
} else {
  await build(options);
  // eslint-disable-next-line no-console
  console.log("built " + outfile);
}
